//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByDSync.Schema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ByDMirrorEntities : DbContext
    {
        public ByDMirrorEntities()
            : base("name=ByDMirrorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gen_ledger> gen_ledger { get; set; }
        public virtual DbSet<journal_entries> journal_entries { get; set; }
        public virtual DbSet<profit_center> profit_center { get; set; }
        public virtual DbSet<project> projects { get; set; }
    }
}
