//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByDSync.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class enum_container
    {
        public string enumNumber { get; set; }
        public string enumDescription { get; set; }
        public string enumTypeId { get; set; }
        public string enumType { get; set; }
    }
}
