//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByDSync.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal_entries
    {
        public string C_uid { get; set; }
        public string gl_act { get; set; }
        public string gl_acct_type { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> changed_date { get; set; }
        public Nullable<System.DateTime> posting_date { get; set; }
        public string jour_id { get; set; }
        public Nullable<int> debit_credit { get; set; }
        public Nullable<int> fiscal_year { get; set; }
        public string created_by { get; set; }
        public string changed_by { get; set; }
        public Nullable<decimal> comp_cur_amt { get; set; }
        public Nullable<decimal> item_cur_amt { get; set; }
        public Nullable<decimal> tran_cur_amt { get; set; }
        public string jour_number { get; set; }
    }
}
