//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByDSync.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class profit_center
    {
        public string C_uid { get; set; }
        public string profit_center_uuid { get; set; }
        public string profit_center_id { get; set; }
        public string profit_center_name { get; set; }
        public string org_center_id { get; set; }
        public Nullable<int> for_plan { get; set; }
        public Nullable<int> for_post { get; set; }
        public string manager_pos { get; set; }
        public string manager_id { get; set; }
    }
}
