//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByDSync.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_task
    {
        public string C_uid { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> changed_on { get; set; }
        public string task_id { get; set; }
        public string project_uid { get; set; }
        public string project_id { get; set; }
        public string task_resp_unit { get; set; }
        public string proj_resp_unit { get; set; }
    }
}
