//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByDSync.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public string C_uid { get; set; }
        public string project_id { get; set; }
        public string project_uuid { get; set; }
        public string project_type { get; set; }
        public Nullable<System.DateTime> projActStaDate { get; set; }
        public Nullable<System.DateTime> projActEndDate { get; set; }
        public string proj_desc { get; set; }
        public string profit_center_id { get; set; }
        public string cost_ctr_id_respunit { get; set; }
        public string cost_center_type { get; set; }
        public string cost_center_id { get; set; }
        public string customer { get; set; }
        public string company { get; set; }
        public string status { get; set; }
        public string risk_level { get; set; }
        public Nullable<int> onhold { get; set; }
    }
}
