//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByDSync.Schema
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ReportGL
    {
        public string C_uid { get; set; }
        [DisplayName("Posting Date")]
        public Nullable<System.DateTime> Posting_Date { get; set; }
        [DisplayName("Journal ID")]
        public string Journal_ID { get; set; }
        [DisplayName("GL Account")]
        public string GL_Account { get; set; }
        [DisplayName("Amount")]
        public Nullable<decimal> Amount { get; set; }
        [DisplayName("Debit/Credit")]
        public string Dr_Cr { get; set; }
        [DisplayName("Profit Center ID")]
        public string Profit_Center { get; set; }
        [DisplayName("Project ID")]
        public string Project_ID { get; set; }
        [DisplayName("Custom Code 3")]
        public string Custom_Code_3 { get; set; }
        [DisplayName("Funding Source")]
        public string Funding_Source_1 { get; set; }
    }
}
