//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByDSync.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportGL
    {
        public string C_uid { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public string Journal_ID { get; set; }
        public string GL_Account { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Dr_Cr { get; set; }
        public string Profit_Center { get; set; }
        public string Project_ID { get; set; }
        public string Custom_Code_3 { get; set; }
        public string Funding_Source_1 { get; set; }
        public string GL_Account_Name { get; set; }
        public string Account_Type { get; set; }
        public string Department_No_ { get; set; }
        public string Department_Name { get; set; }
        public string Project_Name { get; set; }
        public string Supplier_Name { get; set; }
        public string Document_Source_Type { get; set; }
        public string Description { get; set; }
    }
}
