//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByDSync.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public string C_uid { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<System.DateTime> changed_on { get; set; }
        public string supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_email { get; set; }
        public string supplier_adr { get; set; }
        public string supplier_pobox { get; set; }
        public string supplier_postcode { get; set; }
        public string supplier_street { get; set; }
        public string supplier_city { get; set; }
        public string supplier_state { get; set; }
        public string supplier_country { get; set; }
        public string supplier_ind_code { get; set; }
        public string supplier_ind_sys { get; set; }
        public string supplier_phone { get; set; }
    }
}
